In [1]:
import pandas as pd
import matplotlib as plt
import json
from datetime import datetime, timedelta
df_fall_26 = pd.read_csv('output/fall_26.csv')
df_spring_26 = pd.read_csv('output/spring_26.csv')
df_fall_25 = pd.read_csv('output/fall_25_new_scrape.csv')
desired_codes = ['SEAS', 'SAS'] 
df_fall_26
df_spring_26
df_fall_25
#group class times

def group_class(df, term):
    # drop rows with missing days/time
    df = df.dropna(subset=['days'])
    df['start_time'] = pd.to_datetime(df['start_time'], format='%H:%M')
    df['end_time'] = pd.to_datetime(df['end_time'], format='%H:%M')

    df['days'] = df['days'].str.split().str[0]


    day_map = {
        'M': 'Monday',
        'T': 'Tuesday',
        'W': 'Wednesday',
        'R': 'Thursday',
        'F': 'Friday'
    }
    df['days'] = df['days'].fillna('').astype(str)

    df['days'] = df['days'].apply(
        lambda x: [day_map.get(d) for d in x if d in day_map]
    )
    df = df.explode('days').reset_index(drop=True)

    time_bins = pd.date_range("08:00", "20:00", freq="30min").time

    rows = []

    for _, row in df.iterrows():
        day = row['days']
        start = row['start_time'].time()
        end = row['end_time'].time()

        for t in time_bins:
            # convert time → minutes since midnight
            t_minutes = t.hour * 60 + t.minute
            bin_start_minutes = t_minutes
            bin_end_minutes = t_minutes + 30

            start_minutes = start.hour * 60 + start.minute
            end_minutes = end.hour * 60 + end.minute

            # overlap condition
            if start_minutes < bin_end_minutes and end_minutes > bin_start_minutes:
                rows.append({
                    'Day': day,
                    'Time': t
                })

    binned_df = pd.DataFrame(rows)
    # binned_df.to_csv(f"filtered_{term}.csv")
    result = (
        binned_df
        .groupby(['Day', 'Time'])
        .size()
        .reset_index(name='Share')
    )

    day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

    result['Day'] = pd.Categorical(result['Day'], categories=day_order, ordered=True)
    result['Time'] = pd.to_datetime(result['Time'].astype(str)).dt.time

    result = result.sort_values(['Day', 'Time'])

    result.to_csv(f'{term}.csv', index=False)

    return result
# grad_pattern = r'.{4}G'
# remove = df['course.course_identifier'].str.contains(grad_pattern, regex=True, na=False)
# df_undergrad = df[~remove]
# df_undergrad

fall_filtered_df = df_fall_26[df_fall_26['school_code'].isin(desired_codes)]
display(fall_filtered_df.shape[0])
# display(fall_filtered_df)

fall_filtered_df = fall_filtered_df.dropna(subset=['days'])
fall_filtered_df = fall_filtered_df.dropna(subset=['end_time'])
fall_filtered_df = fall_filtered_df.dropna(subset=['start_time'])
fall_filtered_df.to_csv('fall_26_school.csv')
display(fall_filtered_df.shape[0])

# spring_filtered_df = df_spring_26[df_spring_26['school_code'].isin(desired_codes)]
# display(spring_filtered_df.shape[0])

df = fall_filtered_df.copy()
display(group_class(df, 'fall 26'))


# spring_filtered_df = df_spring_26[df_spring_26['school_code'].isin(desired_codes)]
# display(fall_filtered_df.shape[0])
# display(fall_filtered_df)
spring_filtered_df = df_spring_26[df_spring_26['school_code'].isin(desired_codes)]
spring_filtered_df = spring_filtered_df.dropna(subset=['days'])
spring_filtered_df = spring_filtered_df.dropna(subset=['end_time'])
spring_filtered_df = spring_filtered_df.dropna(subset=['start_time'])

df = spring_filtered_df.copy()
display(group_class(df, 'spring 26'))



# fall_25_filtered_df = df_fall_25[df_spring_26['school_code'].isin(desired_codes)]
# display(fall_filtered_df.shape[0])
# display(fall_filtered_df)
fall_25_filtered_df = df_fall_25[df_fall_25['school_code'].isin(desired_codes)]
fall_25_filtered_df = fall_25_filtered_df.dropna(subset=['days'])
fall_25_filtered_df = fall_25_filtered_df.dropna(subset=['end_time'])
fall_25_filtered_df = fall_25_filtered_df.dropna(subset=['start_time'])

df = fall_25_filtered_df.copy()
display(group_class(df, 'fall 25'))

2630

1911

/var/folders/zl/l01js9_527d_nstkmhybfn0c0000gn/T/ipykernel_17661/3274768487.py:74: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  result['Time'] = pd.to_datetime(result['Time'].astype(str)).dt.time

       Day      Time  Share
25  Monday  08:00:00     11
26  Monday  08:30:00     49
27  Monday  09:00:00     57
28  Monday  09:30:00     57
29  Monday  10:00:00    115
..     ...       ...    ...
20  Friday  18:00:00      7
21  Friday  18:30:00      7
22  Friday  19:00:00      3
23  Friday  19:30:00      4
24  Friday  20:00:00      2

[125 rows x 3 columns]

/var/folders/zl/l01js9_527d_nstkmhybfn0c0000gn/T/ipykernel_17661/3274768487.py:74: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  result['Time'] = pd.to_datetime(result['Time'].astype(str)).dt.time

       Day      Time  Share
22  Monday  08:00:00     10
23  Monday  08:30:00     54
24  Monday  09:00:00     62
25  Monday  09:30:00     63
26  Monday  10:00:00    145
..     ...       ...    ...
17  Friday  16:30:00     19
18  Friday  17:00:00     11
19  Friday  17:30:00      7
20  Friday  18:00:00      6
21  Friday  18:30:00      6

[122 rows x 3 columns]

/var/folders/zl/l01js9_527d_nstkmhybfn0c0000gn/T/ipykernel_17661/3274768487.py:74: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  result['Time'] = pd.to_datetime(result['Time'].astype(str)).dt.time

       Day      Time  Share
25  Monday  08:00:00     11
26  Monday  08:30:00     56
27  Monday  09:00:00     67
28  Monday  09:30:00     68
29  Monday  10:00:00    136
..     ...       ...    ...
20  Friday  18:00:00     10
21  Friday  18:30:00      9
22  Friday  19:00:00      6
23  Friday  19:30:00      6
24  Friday  20:00:00      2

[125 rows x 3 columns]