In [98]:
import pandas as pd
import matplotlib as plt

In [100]:
df = pd.read_csv('Downloads/fall_26.csv')

In [102]:
df

,course_identifier,dept_code,school_code,course_name,term,section,call_number,instructor,start_time,end_time,days
0,AFASG4990,AFAM,SAS,AFR-AMER RESEARCH-WRITING,20263,001,12141,Rachel Grace Newman,12:10,14:00,R 12:10PM-2:00PM
1,AFASG4100,AFAM,SAS,AF-AM: PRO SEMINAR,20263,001,13210,Farah Griffin,14:10,16:00,T 2:10PM-4:00PM
2,AFASG4014,AFAM,SAS,Assurance of Infinity: In the Caribbean,20263,001,14264,Rachel Grace Newman,14:10,16:00,R 2:10PM-4:00PM
3,AFASG4010,AFAM,SAS,Reading the works of Jamaica Kincaid,20263,001,12308,Edwidge Danticat,16:10,18:00,M 4:10PM-6:00PM
4,AFASW4003,AFAM,SAS,Writing and Editing the Black Studies Journal,20263,001,14265,Jafari S Allen,16:10,18:00,T 4:10PM-6:00PM
...,...,...,...,...,...,...,...,...,...,...,...
4413,WMSTW4210,WSTB,BCOL,BLACK GEOGRAPHIES,20263,001,599,Marisa Solomon,16:10,18:00,R 4:10PM-6:00PM
4414,WMSTW3915,WSTB,BCOL,"GENDER, SEXUALITY & POWER IN TRANSNATIONAL PER...",20263,002,897,Manijeh Moradian,12:10,14:00,T 12:10PM-2:00PM
4415,WMSTV3525,WSTB,BCOL,Senior Seminar I (Barnard),20263,001,597,Manijeh Moradian,14:10,16:00,W 2:10PM-4:00PM
4416,WMSTV3525,WSTB,BCOL,Senior Seminar I (Barnard),20263,002,875,Janet Jakobsen,09:00,10:50,W 9:00AM-10:50AM
4417,WMSTBC1006,WSTB,BCOL,Introduction to Environmental Humanities,20263,001,590,Ashley Dawson,10:10,11:25,MW 10:10AM-11:25AM

In [104]:
grad_pattern = r'.{4}G'
remove = df['course_identifier'].str.contains(grad_pattern, regex=True, na=False)
df_undergrad = df[~remove]
df_undergrad

desired_codes = ['SEAS', 'SAS'] 

df_filtered = df[df['school_code'].isin(desired_codes)]
df_filtered

,course_identifier,dept_code,school_code,course_name,term,section,call_number,instructor,start_time,end_time,days
0,AFASG4990,AFAM,SAS,AFR-AMER RESEARCH-WRITING,20263,001,12141,Rachel Grace Newman,12:10,14:00,R 12:10PM-2:00PM
1,AFASG4100,AFAM,SAS,AF-AM: PRO SEMINAR,20263,001,13210,Farah Griffin,14:10,16:00,T 2:10PM-4:00PM
2,AFASG4014,AFAM,SAS,Assurance of Infinity: In the Caribbean,20263,001,14264,Rachel Grace Newman,14:10,16:00,R 2:10PM-4:00PM
3,AFASG4010,AFAM,SAS,Reading the works of Jamaica Kincaid,20263,001,12308,Edwidge Danticat,16:10,18:00,M 4:10PM-6:00PM
4,AFASW4003,AFAM,SAS,Writing and Editing the Black Studies Journal,20263,001,14265,Jafari S Allen,16:10,18:00,T 4:10PM-6:00PM
...,...,...,...,...,...,...,...,...,...,...,...
4210,STATW4203,STAT,SAS,PROBABILITY THEORY,20263,003,14573,Banu Baydil,18:10,19:25,TR 6:10PM-7:25PM
4211,STATW4001,STAT,SAS,INTRODUCTION TO PROBABILITY AND STATISTICS,20263,001,14570,Banu Baydil,18:10,19:25,MW 6:10PM-7:25PM
4212,STATG3108,STAT,SAS,APPLIED DEEP LEARNING AND AI,20263,001,14569,Parijat Dube,18:10,19:25,TR 6:10PM-7:25PM
4213,STATW1001,STAT,SAS,INTRO TO STATISTICAL REASONING,20263,001,14548,Tian Zheng,10:10,11:25,TR 10:10AM-11:25AM
4214,STATW1001,STAT,SAS,INTRO TO STATISTICAL REASONING,20263,002,14549,Anthony Donoghue,18:10,19:25,MW 6:10PM-7:25PM

In [9]:
from IPython.display import FileLink
filtered_df.to_csv('SEAS_FAS_only.csv', index=False)
FileLink('SEAS_FAS_only.csv')

C:\Users\emiik\SEAS_FAS_only.csv

In [112]:
prefixes = ('10', '11', '12', '13')
df_filtered['contains'] = df_filtered['start_time'].str.startswith(prefixes)

C:\Users\emiik\AppData\Local\Temp\ipykernel_31572\737945348.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['contains'] = df_filtered['start_time'].str.startswith(prefixes)

In [118]:
department_summary = df_filtered.groupby('dept_code')['contains'].agg(
        total_types='count',
        matching_types='sum'
    )
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(department_summary)
department_summary.to_csv('department_summary.csv')

           total_types matching_types
dept_code
AFAM                10              5
AHAR                24              8
AMST                 5              0
ANTH                28             15
APAM                38             24
ASTR                11              5
BINF                 1          False
BIOS                52             25
BMEN                24             18
CCLS                 7              4
CEEM                23              8
CGTH                 6              2
CHEM               129             45
CLAS                29             10
CLST                 0              0
COGS                 2              1
COLL                 2              1
COMS               105             46
CORE               269             94
CSER                10              4
CSHR                17              5
DGLO                 0              0
EALC                97             42
ECON                76             34
EEEB                27              7
EI                   9              3
ELEN                52             22
ENCL                41             17
ENGI                29             13
FRRP                40             18
GERL                22              8
GSAS                 1           True
HIST                62             25
IIJS                 5              5
ITAL                24             12
MECE                37             18
MELC                78             37
MRST                 1           True
MUSI                37             19
ORHS                 5              1
PHED                63             31
PHIL                19              8
PHYS               119             29
POLS                60             25
PSYC                50             22
RELI                 9              4
RERS                 2              1
SLAL                32             18
SOCI                28              7
STAT                94             37

In [126]:
department_summary['percentage_matching'] = (
    department_summary['matching_types'] / department_summary['total_types'].replace(0, float('nan'))
) * 100

department_summary.to_csv('department_summary.csv')
display(department_summary)

           total_types matching_types percentage_matching
dept_code
AFAM                10              5                50.0
AHAR                24              8           33.333333
AMST                 5              0                 0.0
ANTH                28             15           53.571429
APAM                38             24           63.157895
ASTR                11              5           45.454545
BINF                 1          False                 0.0
BIOS                52             25           48.076923
BMEN                24             18                75.0
CCLS                 7              4           57.142857
CEEM                23              8           34.782609
CGTH                 6              2           33.333333
CHEM               129             45           34.883721
CLAS                29             10           34.482759
CLST                 0              0                 NaN
COGS                 2              1                50.0
COLL                 2              1                50.0
COMS               105             46           43.809524
CORE               269             94           34.944238
CSER                10              4                40.0
CSHR                17              5           29.411765
DGLO                 0              0                 NaN
EALC                97             42           43.298969
ECON                76             34           44.736842
EEEB                27              7           25.925926
EI                   9              3           33.333333
ELEN                52             22           42.307692
ENCL                41             17           41.463415
ENGI                29             13           44.827586
FRRP                40             18                45.0
GERL                22              8           36.363636
GSAS                 1           True               100.0
HIST                62             25           40.322581
IIJS                 5              5               100.0
ITAL                24             12                50.0
MECE                37             18           48.648649
MELC                78             37           47.435897
MRST                 1           True               100.0
MUSI                37             19           51.351351
ORHS                 5              1                20.0
PHED                63             31           49.206349
PHIL                19              8           42.105263
PHYS               119             29           24.369748
POLS                60             25           41.666667
PSYC                50             22                44.0
RELI                 9              4           44.444444
RERS                 2              1                50.0
SLAL                32             18               56.25
SOCI                28              7                25.0
STAT                94             37           39.361702

In [136]:
department_summary['percentage_matching'] = pd.to_numeric(department_summary['percentage_matching'], errors='coerce')
top_20_departments = department_summary.sort_values(by='percentage_matching', ascending=False).head(20)
top_20_departments_2 = department_summary.nlargest(20, 'percentage_matching')

In [138]:
print(top_20_departments)
print(top_20_departments_2)

           total_types matching_types  percentage_matching
dept_code
GSAS                 1           True           100.000000
IIJS                 5              5           100.000000
MRST                 1           True           100.000000
BMEN                24             18            75.000000
APAM                38             24            63.157895
CCLS                 7              4            57.142857
SLAL                32             18            56.250000
ANTH                28             15            53.571429
MUSI                37             19            51.351351
COGS                 2              1            50.000000
ITAL                24             12            50.000000
COLL                 2              1            50.000000
AFAM                10              5            50.000000
RERS                 2              1            50.000000
PHED                63             31            49.206349
MECE                37             18            48.648649
BIOS                52             25            48.076923
MELC                78             37            47.435897
ASTR                11              5            45.454545
FRRP                40             18            45.000000
           total_types matching_types  percentage_matching
dept_code
GSAS                 1           True           100.000000
IIJS                 5              5           100.000000
MRST                 1           True           100.000000
BMEN                24             18            75.000000
APAM                38             24            63.157895
CCLS                 7              4            57.142857
SLAL                32             18            56.250000
ANTH                28             15            53.571429
MUSI                37             19            51.351351
AFAM                10              5            50.000000
COGS                 2              1            50.000000
COLL                 2              1            50.000000
ITAL                24             12            50.000000
RERS                 2              1            50.000000
PHED                63             31            49.206349
MECE                37             18            48.648649
BIOS                52             25            48.076923
MELC                78             37            47.435897
ASTR                11              5            45.454545
FRRP                40             18            45.000000

In [20]:
df_fall = pd.read_csv('Downloads/fall_26.csv')
df_fall

,course_identifier,dept_code,school_code,course_name,term,section,call_number,instructor,start_time,end_time,days
0,AFASG4990,AFAM,SAS,AFR-AMER RESEARCH-WRITING,20263,001,12141,Rachel Grace Newman,12:10,14:00,R 12:10PM-2:00PM
1,AFASG4100,AFAM,SAS,AF-AM: PRO SEMINAR,20263,001,13210,Farah Griffin,14:10,16:00,T 2:10PM-4:00PM
2,AFASG4014,AFAM,SAS,Assurance of Infinity: In the Caribbean,20263,001,14264,Rachel Grace Newman,14:10,16:00,R 2:10PM-4:00PM
3,AFASG4010,AFAM,SAS,Reading the works of Jamaica Kincaid,20263,001,12308,Edwidge Danticat,16:10,18:00,M 4:10PM-6:00PM
4,AFASW4003,AFAM,SAS,Writing and Editing the Black Studies Journal,20263,001,14265,Jafari S Allen,16:10,18:00,T 4:10PM-6:00PM
...,...,...,...,...,...,...,...,...,...,...,...
4413,WMSTW4210,WSTB,BCOL,BLACK GEOGRAPHIES,20263,001,599,Marisa Solomon,16:10,18:00,R 4:10PM-6:00PM
4414,WMSTW3915,WSTB,BCOL,"GENDER, SEXUALITY & POWER IN TRANSNATIONAL PER...",20263,002,897,Manijeh Moradian,12:10,14:00,T 12:10PM-2:00PM
4415,WMSTV3525,WSTB,BCOL,Senior Seminar I (Barnard),20263,001,597,Manijeh Moradian,14:10,16:00,W 2:10PM-4:00PM
4416,WMSTV3525,WSTB,BCOL,Senior Seminar I (Barnard),20263,002,875,Janet Jakobsen,09:00,10:50,W 9:00AM-10:50AM
4417,WMSTBC1006,WSTB,BCOL,Introduction to Environmental Humanities,20263,001,590,Ashley Dawson,10:10,11:25,MW 10:10AM-11:25AM

In [28]:
df_fall25 = pd.read_csv('Downloads/fall-25-all.csv')
df_fall25

,course_identifier,course_name,subject_code,subject_name,school_code,school_name,section,call_number,instructors,enrollment_count,enrollment_max,enrollment_status,days_times,mil_time_from,mil_time_to
0,AFASW4033,HARLEM AND HAITI,AFAS,NaN,SAS,NaN,001,11354,Edwidge Danticat,9.0,12.0,O,R 2:10PM-4:00PM,14:10,16:00
1,AFASW3943,Senior Pro Seminar,AFAS,NaN,SAS,NaN,001,13522,Farah Griffin,6.0,12.0,O,W 12:10PM-2:00PM,12:10,14:00
2,AFASC3930,TOPICS IN THE BLACK EXPERIENCE,AFAS,NaN,SAS,NaN,002,19851,Nyle Fort,1.0,12.0,O,M 12:10PM-2:00PM,12:10,14:00
3,AFASC3901,INDEPENDENT STDY-UNDERGRADUATE,AFAS,NaN,SAS,NaN,001,11366,Farah Griffin,1.0,3.0,O,NaN,NaN,NaN
4,AFASC3901,INDEPENDENT STDY-UNDERGRADUATE,AFAS,NaN,SAS,NaN,002,11367,Brandi Summers,1.0,3.0,O,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166,WMSTV3525,Senior Seminar I (Barnard),WMST,NaN,BCOL,NaN,001,162,Manijeh Moradian,8.0,9.0,O,R 10:10AM-12:00PM,10:10,12:00
8167,WMSTV3525,Senior Seminar I (Barnard),WMST,NaN,BCOL,NaN,002,163,Alexander Pittman,7.0,8.0,O,R 2:10PM-4:00PM,14:10,16:00
8168,WMSTBC3514,HIST APPROACHES FEMINIST QUES,WMST,NaN,BCOL,NaN,001,744,Lisa Duggan,19.0,20.0,O,T 12:10PM-2:00PM,12:10,14:00
8169,WMSTBC3504,GENDERED CONTROVERSIES,WMST,NaN,BCOL,NaN,001,978,Sandra Moyano-Ariza,14.0,24.0,O,M 2:10PM-4:00PM,14:10,16:00
8170,WMSTBC1006,Introduction to Environmental Humanities,WMST,NaN,BCOL,NaN,001,60,Ashley Dawson,25.0,70.0,O,MW 10:10AM-11:25AM,10:10,11:25

In [30]:
course_prefixes = ['MATH', 'POLS', 'ECON', 'PSYC', 'ENGL','HIST']
filtered_df_fall = df_fall[df_fall.course_identifier.str.startswith(tuple(course_prefixes))]
filtered_df_fall

,course_identifier,dept_code,school_code,course_name,term,section,call_number,instructor,start_time,end_time,days
121,ENGLZ0850,AMLP,SPEC,INTL TEACHING FELLOWS TRAINING,20263,001,11025,Lydia Fass,18:10,20:00,MW 6:10PM-8:00PM
122,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,001,11021,NaN,NaN,NaN,NaN
123,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,002,11022,NaN,NaN,NaN,NaN
124,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,003,11023,NaN,NaN,NaN,NaN
125,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,004,11024,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3864,PSYCW1980,PSYC,SAS,Zuckerman Institute Neuroscience and Cognitive...,20263,001,14277,Sarah Demoya,16:10,17:25,W 4:10PM-5:25PM
3865,PSYCW1951,PSYC,SAS,Cells and Circuits Lab,20263,001,10646,Sarah Demoya,10:10,12:00,F 10:10AM-12:00PM
3866,PSYCW1950,PSYC,SAS,Neuroscience Methods: Cells and Circuits,20263,001,10645,Sarah Demoya,10:10,12:00,R 10:10AM-12:00PM
3867,PSYCW1001,PSYC,SAS,THE SCIENCE OF PSYCHOLOGY,20263,001,10631,Patricia G Lindemann,13:10,14:25,TR 1:10PM-2:25PM
3868,PSYCW1001,PSYC,SAS,THE SCIENCE OF PSYCHOLOGY,20263,002,10633,Natalie Brito,10:10,11:25,TR 10:10AM-11:25AM

In [26]:
filtered_df_fall.to_csv('filtered_fall_classes.csv', index=False)

In [101]:
course_prefixes = ['MATH', 'POLS', 'ECON', 'PSYC', 'ENGL']
filtered_df_fall25 = df_fall25[df_fall25.course_identifier.str.startswith(tuple(course_prefixes))]
filtered_df_fall25
filtered_df_fall25.to_csv('filtered_spring_classes.csv', index=False)

In [103]:
# analysis of full or over enrolled classes
df_full_spring26 = pd.read_csv('Downloads/spring-26-al.csv')
df_full_spring26

filtered_df_fullspring26 = df_full_spring26[df_full_spring26.enrollment_status.str.startswith(tuple('F'))]
filtered_df_fullspring26

,course_identifier,course_name,subject_code,subject_name,school_code,school_name,section,call_number,instructors,enrollment_count,enrollment_max,enrollment_status,days_times,mil_time_from,mil_time_to
1,AFASG4004,Turn the TV Off: Black Performance Studies,AFAS,NaN,SAS,NaN,001,15974,Johanna F Almiron,17.0,17.0,F,R 12:10PM-2:00PM,12:10,14:00
9,AFASC3011,Spirit of Justice,AFAS,NaN,SAS,NaN,001,17123,Nyle Fort,18.0,18.0,F,M 10:10AM-12:00PM,10:10,12:00
10,AFASW3004,Introduction to Black Geographies,AFAS,NaN,SAS,NaN,001,10496,Brandi Summers,15.0,15.0,F,W 2:10PM-4:00PM,14:10,16:00
12,AFASW1003,Blackness and Frenchness: A Radical Genealogy,AFAS,NaN,SAS,NaN,001,10536,Veronique Charles,18.0,18.0,F,M 12:10PM-2:00PM,12:10,14:00
23,AFASG4080,TOPICS IN THE BLACK EXPERIENCE,AFAS,NaN,SAS,NaN,005,13264,Erica Hunt,1.0,1.0,F,R 4:10PM-6:00PM,16:10,18:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6946,WRITW1100,BEGINNING FICTION WORKSHOP,WRIT,NaN,SART,NaN,005,12807,Haley Garvin,15.0,15.0,F,W 2:10PM-4:00PM,14:10,16:00
6953,WMSTBC3138,AFFECT AND ACTIVISM,WMST,NaN,BCOL,NaN,001,761,Manijeh Moradian,16.0,16.0,F,T 2:10PM-4:00PM,14:10,16:00
6958,WMSTV4905,Labor and Life: Critiques of Capitalism,WMST,NaN,BCOL,NaN,001,767,Neferti Tadiar,16.0,16.0,F,R 12:10PM-2:00PM,12:10,14:00
6959,WMSTW4330,"SWANA Diasporas: Culture, Politics and Identit...",WMST,NaN,BCOL,NaN,001,766,Manijeh Moradian,14.0,14.0,F,R 10:10AM-12:00PM,10:10,12:00
6963,WMSTW4210,BLACK GEOGRAPHIES,WMST,NaN,BCOL,NaN,001,764,Marisa Solomon,16.0,15.0,F,R 2:10PM-4:00PM,14:10,16:00

In [76]:
time_counts = filtered_df['mil_time_from'].value_counts().reset_index()
percentages = filtered_df['mil_time_from'].value_counts(normalize=True) * 100
time_counts.columns = ['StartTime', 'Frequency']
percentages.columns = ['StartTime', 'Percentage']
print(time_counts)

   StartTime  Frequency
0      16:10        378
1      10:10        348
2      14:10        240
3      13:10        228
4      12:10        151
5      18:10        140
6      14:40        130
7      11:40        128
8      08:40         64
9      15:10         51
10     17:10         41
11     10:00         33
12     17:40         32
13     13:00         30
14     11:10         29
15     09:00         28
16     19:00         27
17     08:10         26
18     09:10         20
19     19:10         16
20     11:00         11
21     12:00         10
22     14:00         10
23     08:50         10
24     19:30          9
25     16:00          9
26     08:00          8
27     15:00          8
28     17:00          7
29     18:00          6
30     12:05          6
31     13:30          6
32     20:10          6
33     14:30          5
34     10:30          5
35     12:30          4
36     09:30          3
37     20:00          3
38     18:30          3
39     11:30          2
40     10:40          2
41     20:30          2
42     12:45          2
43     11:05          2
44     19:35          1
45     17:35          1
46     17:30          1
47     20:15          1
48     19:15          1
49     11:45          1
50     19:40          1
51     10:20          1
52     07:20          1
53     16:20          1
54     16:30          1
55     18:45          1

In [94]:
import datetime as dt

# Step 1: Parse and extract hour
df_filtered['start_time'] = pd.to_datetime(
    df_filtered['start_time'], format='%H:%M', errors='coerce'
)
df_filtered['start_time'] = df_filtered['start_time'].dt.hour

# Step 2: Drop rows where parsing failed
df_filtered = df_filtered.dropna(subset=['start_time'])

# Step 3: Bin into time buckets
hour_bins = [8, 10, 12, 14, 16, 18, 20, 22]
hour_labels = ['8 am - 10 am', '10 am - 12 pm', '12 pm - 2 pm', '2 pm - 4 pm', '4 pm - 6 pm', '6 pm - 8 pm', '8 pm - 10 pm']
df_filtered['time_bucket'] = pd.cut(
    df_filtered['start_time'], bins=hour_bins, labels=hour_labels, right=False
)
percentages = df_filtered['time_bucket'].value_counts(normalize=True) * 100
print(percentages)

time_bucket
10 am - 12 pm    23.076923
4 pm - 6 pm      22.867609
2 pm - 4 pm      19.675563
12 pm - 2 pm     18.001047
6 pm - 8 pm       9.157509
8 am - 10 am      6.855050
8 pm - 10 pm      0.366300
Name: proportion, dtype: float64

C:\Users\emiik\AppData\Local\Temp\ipykernel_31572\2726123851.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['start_time'] = pd.to_datetime(
C:\Users\emiik\AppData\Local\Temp\ipykernel_31572\2726123851.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['start_time'] = df_filtered['start_time'].dt.hour
C:\Users\emiik\AppData\Local\Temp\ipykernel_31572\2726123851.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['time_bucket'] = pd.cut(

In [93]:
print(df['mil_time_from_hr'].unique())
print(df['mil_time_from_hr'].value_counts())
print(df['mil_time_from'].unique())

print(df.columns.tolist())
print(df.head())

[]
Series([], Name: count, dtype: int64)
<DatetimeArray>
[]
Length: 0, dtype: datetime64[ns]
['course_identifier', 'course_name', 'subject_code', 'subject_name', 'school_code', 'school_name', 'section', 'call_number', 'instructors', 'enrollment_count', 'enrollment_max', 'enrollment_status', 'days_times', 'mil_time_from', 'mil_time_to', 'contains', 'mil_time_from_hr', 'time_bucket']
Empty DataFrame
Columns: [course_identifier, course_name, subject_code, subject_name, school_code, school_name, section, call_number, instructors, enrollment_count, enrollment_max, enrollment_status, days_times, mil_time_from, mil_time_to, contains, mil_time_from_hr, time_bucket]
Index: []

In [117]:
# filtering by fall
filtered_df_fullfall26 = filtered_df_fall[filtered_df_fall.enrollment_status.str.startswith(tuple('F'))]
filtered_df_fullfall26

AttributeError: 'DataFrame' object has no attribute 'enrollment_status'

In [145]:
time_counts = filtered_df_fall['start_time'].value_counts().reset_index()
percentages = filtered_df_fall['start_time'].value_counts(normalize=True) * 100
time_counts.columns = ['StartTime', 'Frequency']
percentages.columns = ['StartTime', 'Percentage']
print(time_counts)

             StartTime  Frequency
0  1900-01-01 10:10:00         87
1  1900-01-01 16:10:00         84
2  1900-01-01 14:10:00         63
3  1900-01-01 14:40:00         36
4  1900-01-01 11:40:00         34
5  1900-01-01 13:10:00         32
6  1900-01-01 12:10:00         29
7  1900-01-01 08:40:00         19
8  1900-01-01 18:10:00         14
9  1900-01-01 17:40:00         12
10 1900-01-01 11:00:00         10
11 1900-01-01 09:10:00          7
12 1900-01-01 09:00:00          6
13 1900-01-01 12:00:00          4
14 1900-01-01 13:00:00          3
15 1900-01-01 11:10:00          1
16 1900-01-01 08:10:00          1
17 1900-01-01 18:30:00          1
18 1900-01-01 13:30:00          1
19 1900-01-01 11:30:00          1
20 1900-01-01 12:30:00          1
21 1900-01-01 20:10:00          1

In [105]:
import datetime as dt

# Step 1: Parse directly and extract hour - don't convert to .dt.time first
df_fall['start_time'] = pd.to_datetime(
    df_fall['start_time'], format='%H:%M', errors='coerce'
)
df_fall['start_hour'] = df_fall['start_time'].dt.hour

# Step 2: Drop rows where parsing failed
df_fall = df_fall.dropna(subset=['start_hour'])
df_fall['start_hour'] = df_fall['start_hour'].astype(int)

# Step 3: Bin into time buckets
hour_bins = [8, 10, 12, 14, 16, 18, 20, 22]
hour_labels = ['8 am - 10 am', '10 am - 12 pm', '12 pm - 2 pm', '2 pm - 4 pm', '4 pm - 6 pm', '6 pm - 8 pm', '8 pm - 10 pm']

df_fall['time_bucket'] = pd.cut(
    df_fall['start_hour'], bins=hour_bins, labels=hour_labels, right=False
)

percentages = df_fall['time_bucket'].value_counts(normalize=True) * 100
print(percentages)

time_bucket
10 am - 12 pm    23.287671
4 pm - 6 pm      19.592227
2 pm - 4 pm      17.521504
12 pm - 2 pm     16.629500
6 pm - 8 pm      12.392482
8 am - 10 am      7.677604
8 pm - 10 pm      2.899012
Name: proportion, dtype: float64

C:\Users\emiik\AppData\Local\Temp\ipykernel_29876\800618368.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fall['start_hour'] = df_fall['start_hour'].astype(int)
C:\Users\emiik\AppData\Local\Temp\ipykernel_29876\800618368.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fall['time_bucket'] = pd.cut(

In [57]:
filtered_df_fall

,course_identifier,dept_code,school_code,course_name,term,section,call_number,instructor,start_time,end_time,days
121,ENGLZ0850,AMLP,SPEC,INTL TEACHING FELLOWS TRAINING,20263,001,11025,Lydia Fass,18:10,20:00,MW 6:10PM-8:00PM
122,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,001,11021,NaN,NaN,NaN,NaN
123,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,002,11022,NaN,NaN,NaN,NaN
124,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,003,11023,NaN,NaN,NaN,NaN
125,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,004,11024,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3864,PSYCW1980,PSYC,SAS,Zuckerman Institute Neuroscience and Cognitive...,20263,001,14277,Sarah Demoya,16:10,17:25,W 4:10PM-5:25PM
3865,PSYCW1951,PSYC,SAS,Cells and Circuits Lab,20263,001,10646,Sarah Demoya,10:10,12:00,F 10:10AM-12:00PM
3866,PSYCW1950,PSYC,SAS,Neuroscience Methods: Cells and Circuits,20263,001,10645,Sarah Demoya,10:10,12:00,R 10:10AM-12:00PM
3867,PSYCW1001,PSYC,SAS,THE SCIENCE OF PSYCHOLOGY,20263,001,10631,Patricia G Lindemann,13:10,14:25,TR 1:10PM-2:25PM
3868,PSYCW1001,PSYC,SAS,THE SCIENCE OF PSYCHOLOGY,20263,002,10633,Natalie Brito,10:10,11:25,TR 10:10AM-11:25AM