In [341]:
import pandas as pd
import matplotlib as plt

In [343]:
df = pd.read_csv('Downloads/FINAL_fall_26.csv')

In [345]:
df

print(df['dept_code'].unique())

['AFAM' 'AFSB' 'AHAR' 'AMLP' 'AMSB' 'AMST' 'ANES' 'ANTB' 'ANTH' 'APAM'
 'APAN' 'ARCB' 'ARHB' 'ARPL' 'ARTS' 'ASMB' 'ASTR' 'BIDO' 'BIET' 'BINF'
 'BIOB' 'BIOS' 'BIST' 'BMEN' 'CCLS' 'CEEM' 'CGTH' 'CHEM' 'CHEN' 'CHMB'
 'CLAS' 'CLSB' 'CLST' 'CNAD' 'COGB' 'COGS' 'COLL' 'COMB' 'COMM' 'COMS'
 'CORE' 'CSER' 'CSHR' 'CSOB' 'DEOS' 'DGLO' 'DGOR' 'EAEE' 'EALC' 'ECOB'
 'ECON' 'EDNB' 'EEEB' 'EESC' 'EHSC' 'EI' 'ELEN' 'EMED' 'ENCL' 'ENGB'
 'ENGI' 'ENSB' 'EPID' 'EPIO' 'ERM' 'EXEC' 'FRNB' 'FRRP' 'FYSB' 'FYWB'
 'GAPP' 'GERL' 'GRMB' 'GSAS' 'HCM' 'HIST' 'HRTB' 'HSTB' 'IEOR' 'IIJS'
 'IMGT' 'ISDI' 'ITAL' 'ITLB' 'JOUR' 'LAW' 'LCRS' 'MATH' 'MECE' 'MEDI'
 'MELC' 'MEND' 'MRST' 'MUSB' 'MUSI' 'NOPM' 'NRSB' 'ORHS' 'PEDB' 'PHED'
 'PHIL' 'PHLB' 'PHYB' 'PHYS' 'PLSB' 'PMGT' 'POAN' 'POLS' 'POPF' 'PSYB'
 'PSYC' 'PUBH' 'RELB' 'RELI' 'RERS' 'SCPB' 'SLAL' 'SOCB' 'SOCI' 'SOCW'
 'SOSC' 'SPNB' 'SPPO' 'SPRT' 'STAT' 'SUMA' 'SUSC' 'THEA' 'THEB' 'URSB'
 'WRIT' 'WSTB']

In [351]:
grad_pattern = r'.{4}G'
remove = df['course_identifier'].str.contains(grad_pattern, regex=True, na=False)
df_undergrad = df[~remove]
df_undergrad

#Filtering for SAS & SEAS & NOT labs, recitations, discussion
desired_codes = ['SEAS', 'SAS'] 
desired_type = [r'\bLAB\b', r'\bREC\b', r'\bDISC\b', r'\bDISCUSSION\b', 
                r'\bRECITATION\b', r'\bLABORATORY\b', '-REC', '-DISC', '-LAB',
                'independent study']
pattern = '|'.join(desired_type)

df_filtered = df[
    df['school_code'].isin(desired_codes) & 
    ~df['course_name'].str.contains(pattern, case=False, na=False)
    ].copy()

df_filtered.to_csv('testing.csv')

SAS_codes = [
    # --- Humanities (13 departments) ---
    "AHAR",  # Art History and Archaeology
    "CLAS",  # Classics
    "EALC",  # East Asian Languages and Cultures
    "ENCL",  # English and Comparative Literature
    "FRRP",  # French and Romance Philology
    "GERL",  # Germanic Languages
    "ITAL",  # Italian
    "MELC",  # Middle Eastern, South Asian, and African Studies
    "MUSI",  # Music
    "PHIL",  # Philosophy
    "RELI",  # Religion
    "SLAL",  # Slavic Languages

    # *** (LAIC- Latin American & Iberian Cultures - 3 departments that are housed under LAIC)
    "LAIC",
    "SPPO",
    "SPAN", # Spanish
    "CATL", # Catalan
    "PORT", # Portuguese
    # --- Natural Sciences (9 departments) ---
    "ASTR",  # Astronomy
    "BIOS",  # Biological Sciences
    "CHEM",  # Chemistry
    "EESC",  # Earth and Environmental Sciences  ← NOT in registrar dump — double-check
    "EEEB",  # Ecology, Evolution, and Environmental Biology
    "MATH",  # Mathematics  ← NOT in registrar dump — double-check
    "PHYS",  # Physics
    "PSYC",  # Psychology
    "STAT",  # Statistics

    # --- Social Sciences (6 departments) ---
    "AFAM",  # African American and African Diaspora Studies (you had nothing; "AFAM" is in the list)
    "ANTH",  # Anthropology
    "ECON",  # Economics
    "HIST",  # History
    "POLS",  # Political Science
    "SOCI",  # Sociology
    "CORE"
]

# SEAS — confirmed unchanged
SEAS_codes = [
    "APAM", "BMEN", "CEEM", "CHEN", "COMS",
    "EAEE", "ELEN", "IEOR", "MECE",
]

both_codes = SAS_codes + SEAS_codes

df_filtered = df_filtered[df_filtered['dept_code'].isin(both_codes)].copy() # filter out for ONLY seas and SAS

print(len(df_filtered))

print(f"Original df:        {len(df)}")
print(f"SAS/SEAS only:      {len(df[df['school_code'].isin(desired_codes)])}")
print(f"After pattern filter: {len(df_filtered)}")
print(f"Rows removed:       {len(df[df['school_code'].isin(desired_codes)]) - len(df_filtered)}")

# see what was removed
removed = df[
    df['school_code'].isin(desired_codes) &
    df['course_name'].str.contains(pattern, case=False, na=False)
]
print(removed['course_name'].unique())

2494
Original df:        5177
SAS/SEAS only:      3148
After pattern filter: 2494
Rows removed:       654
['INDEPENDENT STUDY-GRADUATE'
 'Mafias and Other Dangerous Affiliations DISC'
 'MATERIALS SCIENCE LABORATORY' 'LABORATORY IN MATERIALS SCI I'
 'RAD INSTRUMENT/MEASUREMENT LAB' 'ASTRONOMY LAB II' 'ASTRONOMY LAB I'
 'CONTEMPORARY BIOLOGY LAB' 'PROTEOMICS LABORATORY'
 'INDEP BIOLOGICAL RESEARCH - REC' 'LAB IN MOLECULAR BIOLOGY'
 'BIOMEDICAL ENGINEERING LAB I' 'Senior Seminar Discussion Section'
 'GENERAL CHEMISTRY LABORATORY' 'GENERAL CHEMISTRY I - REC'
 'GENERAL CHEMISTRY II-REC' 'PHYSICL-ANALYTICL LABORATORY I'
 'INTENSIVE ORGANIC CHEM LAB' 'ORGANIC CHEM. LABORATORY I'
 'ORGANIC CHEM. LAB I TECHNIQUES' 'ORGANIC CHEMISTRY - REC'
 'Intensive Organic Chemistry II - RECITATION'
 '2ND TERM GEN CHEM(INTENS)-REC' 'INTENSVE GENERAL CHEMISTRY-LAB'
 'GENERAL CHEMISTRY LAB-LECTURE'
 'Warfare in the Ancient Greek World - Discussion Sections'
 'Lab in Computational Biology' 'COMPUTING IN CONTEXT REC'
 'FRONTIERS OF SCIENCE-DISC' 'INTER MACROECONOMICS-DISC'
 'INTER MICROECONOMICS-DISC' 'PRINCIPLES OF ECONOMICS-DISC'
 'INDEPENDENT STUDY' 'INTRO-STAT-ECOLGY/EVOL BIO-LAB'
 'HUMAN ORIGINS & EVOLUTION-DISC' 'SIGNALS & SYSTEMS LABORATORY'
 'CIRCUIT ANALYSIS LABORATORY' 'SOLID ST,MICROWAVE,FBR OPT LAB'
 'DAILY LIFE IN MED EUR-DISC' 'GENDER & SEXUALITY IN AFRICA-DISC'
 'HIST OF SOUTH ASIA I-DISC' 'DISC - History of the City in Latin America'
 'ANC GREEK HIST 800-146 BC-DISC' 'WAR & SOCIETY SINCE 1945-DISC'
 'Making Modern Korea - DISC' 'WEST AFRICA-DISC'
 'THE OTTOMAN EMPIRE-DISCUSSION'
 'Ancient History of the Middle East - DISC'
 'LATIN AMER CIVILIZATION I-DISC' 'US LGBT HIST-DISC'
 'DISC-HEALTH INEQUALITY: MODERN US'
 'Indigenous History of North America - DISC'
 'Shadow of the Sun King: Early Modern France - DISC'
 'Conquests and Transformations: Ireland since 1500 - DISC'
 'World economy, Empire & War: 1900-50 - DISC'
 'DISC - European Intellectual History' 'EARLY RUSS HIST TO 1800-DISC'
 'HONORS MATHEMATICS A-REC' 'ACCELERATED MULTIVARIABLE CALC-REC'
 'MECHANICAL ENGINEERING LAB I' 'Lab-on-a-Chip and Microrobotic Devices'
 'Game of Thrones Discussion Section'
 'Premodern Islamic Worlds-Discussion Section'
 'SUPERVISED INDEPENDENT STUDY' 'INTRO TO EXPERIMENTAL PHYS-LAB'
 'INTRO TO MECH & THERMO - REC' 'GENERAL PHYSICS I LAB'
 'GENERAL PHYSICS I - REC' 'Quantum Physics Laboratory'
 'ELECTRONICS LABORATORY' 'INTERMEDIATE LABORATORY WORK'
 'Physics III: Class/Quantum Wave - Rec'
 'PHYSICS I:MECHANICS/RELATIVITY-REC' 'International Politics Discussion'
 "INT'L POLITICAL ECONOMY-DISC" 'POLITICS IN THE LAB'
 'TOPICS GAME THEORY - DISC'
 'Machine Learning & AI for Social Sciences Discussion'
 'QUANTITATIVE METHODS 3: DISCUSSION' 'QUANTITATIVE METHODS 1 DISCUSSION'
 'PRINC OF QUANT POL RESEARCH 1-DISC'
 'Introduction to American Politics Discussion'
 'MATH & STATS FOR POLI SCI-DISC' 'LATIN AMER POLITICS-DISC'
 'South Asian Politics Discussion' 'EXPERIMENTAL RESEARCH-DISC'
 'SCOPE AND METHODS - DISC'
 'The Rise of the Modern World Economy Discussion'
 'Political Theory I Discussion' 'GOVERNING GLOBAL ECONOMY-DISC'
 'AMERICAN FOREIGN POLICY-DISC' 'STATISTCS-BEHAV SCIENTISTS-LAB'
 'Research Methods: Data Science, Justice, and Social Change - Lab Section'
 'RESEARCH METHODS - SOCIAL COGNITION & EMOTION - LAB'
 'RESEARCH METHODS-HUM BEHAV LAB' 'Cells and Circuits Lab'
 'Chinese Religious Traditions - Discussion'
 'Religion and Nasty Women - Discussion' 'ISLAM-DISCUSSION'
 'Statistics - Graduate Recitation' 'Intro to Statistics Recitation']

In [232]:
from IPython.display import FileLink
filtered_df.to_csv('SEAS_FAS_only.csv', index=False)
FileLink('SEAS_FAS_only.csv')

NameError: name 'filtered_df' is not defined

In [353]:
prefixes = ('10', '11', '12', '13')
df_filtered['contains'] = df_filtered['start_time'].str.startswith(prefixes).copy()

In [355]:
# filtering based off of school_code:

department_summary = df_filtered.groupby('dept_code')['contains'].agg(
        total_types='count',
        matching_types='sum'
    )
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(department_summary)

department_summary.to_csv('department_summary.csv')

           total_types matching_types
dept_code
AFAM                11              6
AHAR                26             10
ANTH                28             15
APAM                35             21
ASTR                 8              5
BIOS                40             17
BMEN                23             17
CEEM                36             16
CHEM                23             10
CHEN                31             16
CLAS                30             13
COMS                94             41
CORE               239             76
EAEE                17              6
EALC                98             42
ECON                76             34
EEEB                20              7
EESC                32             16
ELEN                44             19
ENCL                43             18
FRRP                40             18
GERL                22              8
HIST                57             23
IEOR                64             28
ITAL                24             12
MATH                73             35
MECE                32             17
MELC                64             35
MUSI                36             18
PHIL                19              8
PHYS                25             12
POLS                61             24
PSYC                41             18
RELI                 9              4
SLAL                32             18
SOCI                28              6
SPPO                31             13
STAT                89             34

In [374]:
department_summary['percentage_matching'] = (
    department_summary['matching_types'] / department_summary['total_types'].replace(0, float('nan'))
) * 100

department_summary.to_csv('department_summary.csv')

department_summary['total_types'] = department_summary['total_types'].astype(int)

print(department_summary[department_summary['percentage_matching'] > 40].shape[0])
print(department_summary.shape[0])

display(department_summary.sort_values(by="percentage_matching", ascending=True))

30
38

           total_types matching_types percentage_matching
dept_code
SOCI                28              6           21.428571
CORE               239             76           31.799163
EEEB                20              7                35.0
EAEE                17              6           35.294118
GERL                22              8           36.363636
STAT                89             34           38.202247
AHAR                26             10           38.461538
POLS                61             24           39.344262
HIST                57             23           40.350877
ENCL                43             18           41.860465
SPPO                31             13           41.935484
PHIL                19              8           42.105263
BIOS                40             17                42.5
EALC                98             42           42.857143
ELEN                44             19           43.181818
CLAS                30             13           43.333333
CHEM                23             10           43.478261
COMS                94             41           43.617021
IEOR                64             28               43.75
PSYC                41             18           43.902439
CEEM                36             16           44.444444
RELI                 9              4           44.444444
ECON                76             34           44.736842
FRRP                40             18                45.0
MATH                73             35           47.945205
PHYS                25             12                48.0
EESC                32             16                50.0
ITAL                24             12                50.0
MUSI                36             18                50.0
CHEN                31             16           51.612903
MECE                32             17              53.125
ANTH                28             15           53.571429
AFAM                11              6           54.545455
MELC                64             35             54.6875
SLAL                32             18               56.25
APAM                35             21                60.0
ASTR                 8              5                62.5
BMEN                23             17           73.913043

In [360]:
department_summary['percentage_matching'] = pd.to_numeric(department_summary['percentage_matching'], errors='coerce')
top_20_departments = department_summary.sort_values(by='percentage_matching', ascending=False).head(20)
top_20_departments_2 = department_summary.nlargest(20, 'percentage_matching')

In [362]:
print(top_20_departments)
print(top_20_departments_2)

           total_types matching_types  percentage_matching
dept_code
BMEN                23             17            73.913043
ASTR                 8              5            62.500000
APAM                35             21            60.000000
SLAL                32             18            56.250000
MELC                64             35            54.687500
AFAM                11              6            54.545455
ANTH                28             15            53.571429
MECE                32             17            53.125000
CHEN                31             16            51.612903
EESC                32             16            50.000000
ITAL                24             12            50.000000
MUSI                36             18            50.000000
PHYS                25             12            48.000000
MATH                73             35            47.945205
FRRP                40             18            45.000000
ECON                76             34            44.736842
RELI                 9              4            44.444444
CEEM                36             16            44.444444
PSYC                41             18            43.902439
IEOR                64             28            43.750000
           total_types matching_types  percentage_matching
dept_code
BMEN                23             17            73.913043
ASTR                 8              5            62.500000
APAM                35             21            60.000000
SLAL                32             18            56.250000
MELC                64             35            54.687500
AFAM                11              6            54.545455
ANTH                28             15            53.571429
MECE                32             17            53.125000
CHEN                31             16            51.612903
EESC                32             16            50.000000
ITAL                24             12            50.000000
MUSI                36             18            50.000000
PHYS                25             12            48.000000
MATH                73             35            47.945205
FRRP                40             18            45.000000
ECON                76             34            44.736842
CEEM                36             16            44.444444
RELI                 9              4            44.444444
PSYC                41             18            43.902439
IEOR                64             28            43.750000

In [364]:
df_fall = pd.read_csv('Downloads/fall_26.csv')
df_fall

,course_identifier,dept_code,school_code,course_name,term,section,call_number,instructor,start_time,end_time,days
0,AFASG4990,AFAM,SAS,AFR-AMER RESEARCH-WRITING,20263,001,12141,Rachel Grace Newman,12:10,14:00,R 12:10PM-2:00PM
1,AFASG4100,AFAM,SAS,AF-AM: PRO SEMINAR,20263,001,13210,Farah Griffin,14:10,16:00,T 2:10PM-4:00PM
2,AFASG4014,AFAM,SAS,Assurance of Infinity: In the Caribbean,20263,001,14264,Rachel Grace Newman,14:10,16:00,R 2:10PM-4:00PM
3,AFASG4010,AFAM,SAS,Reading the works of Jamaica Kincaid,20263,001,12308,Edwidge Danticat,16:10,18:00,M 4:10PM-6:00PM
4,AFASW4003,AFAM,SAS,Writing and Editing the Black Studies Journal,20263,001,14265,Jafari S Allen,16:10,18:00,T 4:10PM-6:00PM
...,...,...,...,...,...,...,...,...,...,...,...
4413,WMSTW4210,WSTB,BCOL,BLACK GEOGRAPHIES,20263,001,599,Marisa Solomon,16:10,18:00,R 4:10PM-6:00PM
4414,WMSTW3915,WSTB,BCOL,"GENDER, SEXUALITY & POWER IN TRANSNATIONAL PER...",20263,002,897,Manijeh Moradian,12:10,14:00,T 12:10PM-2:00PM
4415,WMSTV3525,WSTB,BCOL,Senior Seminar I (Barnard),20263,001,597,Manijeh Moradian,14:10,16:00,W 2:10PM-4:00PM
4416,WMSTV3525,WSTB,BCOL,Senior Seminar I (Barnard),20263,002,875,Janet Jakobsen,09:00,10:50,W 9:00AM-10:50AM
4417,WMSTBC1006,WSTB,BCOL,Introduction to Environmental Humanities,20263,001,590,Ashley Dawson,10:10,11:25,MW 10:10AM-11:25AM

In [366]:
df_fall25 = pd.read_csv('Downloads/fall-25-all.csv')
df_fall25

,course_identifier,course_name,subject_code,subject_name,school_code,school_name,section,call_number,instructors,enrollment_count,enrollment_max,enrollment_status,days_times,mil_time_from,mil_time_to
0,AFASW4033,HARLEM AND HAITI,AFAS,NaN,SAS,NaN,001,11354,Edwidge Danticat,9.0,12.0,O,R 2:10PM-4:00PM,14:10,16:00
1,AFASW3943,Senior Pro Seminar,AFAS,NaN,SAS,NaN,001,13522,Farah Griffin,6.0,12.0,O,W 12:10PM-2:00PM,12:10,14:00
2,AFASC3930,TOPICS IN THE BLACK EXPERIENCE,AFAS,NaN,SAS,NaN,002,19851,Nyle Fort,1.0,12.0,O,M 12:10PM-2:00PM,12:10,14:00
3,AFASC3901,INDEPENDENT STDY-UNDERGRADUATE,AFAS,NaN,SAS,NaN,001,11366,Farah Griffin,1.0,3.0,O,NaN,NaN,NaN
4,AFASC3901,INDEPENDENT STDY-UNDERGRADUATE,AFAS,NaN,SAS,NaN,002,11367,Brandi Summers,1.0,3.0,O,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166,WMSTV3525,Senior Seminar I (Barnard),WMST,NaN,BCOL,NaN,001,162,Manijeh Moradian,8.0,9.0,O,R 10:10AM-12:00PM,10:10,12:00
8167,WMSTV3525,Senior Seminar I (Barnard),WMST,NaN,BCOL,NaN,002,163,Alexander Pittman,7.0,8.0,O,R 2:10PM-4:00PM,14:10,16:00
8168,WMSTBC3514,HIST APPROACHES FEMINIST QUES,WMST,NaN,BCOL,NaN,001,744,Lisa Duggan,19.0,20.0,O,T 12:10PM-2:00PM,12:10,14:00
8169,WMSTBC3504,GENDERED CONTROVERSIES,WMST,NaN,BCOL,NaN,001,978,Sandra Moyano-Ariza,14.0,24.0,O,M 2:10PM-4:00PM,14:10,16:00
8170,WMSTBC1006,Introduction to Environmental Humanities,WMST,NaN,BCOL,NaN,001,60,Ashley Dawson,25.0,70.0,O,MW 10:10AM-11:25AM,10:10,11:25

In [368]:
course_prefixes = ['MATH', 'POLS', 'ECON', 'PSYC', 'ENGL','HIST']
filtered_df_fall = df_fall[df_fall.course_identifier.str.startswith(tuple(course_prefixes))]
filtered_df_fall

,course_identifier,dept_code,school_code,course_name,term,section,call_number,instructor,start_time,end_time,days
121,ENGLZ0850,AMLP,SPEC,INTL TEACHING FELLOWS TRAINING,20263,001,11025,Lydia Fass,18:10,20:00,MW 6:10PM-8:00PM
122,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,001,11021,NaN,NaN,NaN,NaN
123,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,002,11022,NaN,NaN,NaN,NaN
124,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,003,11023,NaN,NaN,NaN,NaN
125,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,004,11024,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3864,PSYCW1980,PSYC,SAS,Zuckerman Institute Neuroscience and Cognitive...,20263,001,14277,Sarah Demoya,16:10,17:25,W 4:10PM-5:25PM
3865,PSYCW1951,PSYC,SAS,Cells and Circuits Lab,20263,001,10646,Sarah Demoya,10:10,12:00,F 10:10AM-12:00PM
3866,PSYCW1950,PSYC,SAS,Neuroscience Methods: Cells and Circuits,20263,001,10645,Sarah Demoya,10:10,12:00,R 10:10AM-12:00PM
3867,PSYCW1001,PSYC,SAS,THE SCIENCE OF PSYCHOLOGY,20263,001,10631,Patricia G Lindemann,13:10,14:25,TR 1:10PM-2:25PM
3868,PSYCW1001,PSYC,SAS,THE SCIENCE OF PSYCHOLOGY,20263,002,10633,Natalie Brito,10:10,11:25,TR 10:10AM-11:25AM

In [370]:
filtered_df_fall.to_csv('filtered_fall_classes.csv', index=False)

In [253]:
course_prefixes = ['MATH', 'POLS', 'ECON', 'PSYC', 'ENGL']
filtered_df_fall25 = df_fall25[df_fall25.course_identifier.str.startswith(tuple(course_prefixes))]
filtered_df_fall25
filtered_df_fall25.to_csv('filtered_spring_classes.csv', index=False)

In [255]:
# analysis of full or over enrolled classes
df_full_spring26 = pd.read_csv('Downloads/spring-26-al.csv')
df_full_spring26

filtered_df_fullspring26 = df_full_spring26[df_full_spring26.enrollment_status.str.startswith(tuple('F'))]
filtered_df_fullspring26

,course_identifier,course_name,subject_code,subject_name,school_code,school_name,section,call_number,instructors,enrollment_count,enrollment_max,enrollment_status,days_times,mil_time_from,mil_time_to
1,AFASG4004,Turn the TV Off: Black Performance Studies,AFAS,NaN,SAS,NaN,001,15974,Johanna F Almiron,17.0,17.0,F,R 12:10PM-2:00PM,12:10,14:00
9,AFASC3011,Spirit of Justice,AFAS,NaN,SAS,NaN,001,17123,Nyle Fort,18.0,18.0,F,M 10:10AM-12:00PM,10:10,12:00
10,AFASW3004,Introduction to Black Geographies,AFAS,NaN,SAS,NaN,001,10496,Brandi Summers,15.0,15.0,F,W 2:10PM-4:00PM,14:10,16:00
12,AFASW1003,Blackness and Frenchness: A Radical Genealogy,AFAS,NaN,SAS,NaN,001,10536,Veronique Charles,18.0,18.0,F,M 12:10PM-2:00PM,12:10,14:00
23,AFASG4080,TOPICS IN THE BLACK EXPERIENCE,AFAS,NaN,SAS,NaN,005,13264,Erica Hunt,1.0,1.0,F,R 4:10PM-6:00PM,16:10,18:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6946,WRITW1100,BEGINNING FICTION WORKSHOP,WRIT,NaN,SART,NaN,005,12807,Haley Garvin,15.0,15.0,F,W 2:10PM-4:00PM,14:10,16:00
6953,WMSTBC3138,AFFECT AND ACTIVISM,WMST,NaN,BCOL,NaN,001,761,Manijeh Moradian,16.0,16.0,F,T 2:10PM-4:00PM,14:10,16:00
6958,WMSTV4905,Labor and Life: Critiques of Capitalism,WMST,NaN,BCOL,NaN,001,767,Neferti Tadiar,16.0,16.0,F,R 12:10PM-2:00PM,12:10,14:00
6959,WMSTW4330,"SWANA Diasporas: Culture, Politics and Identit...",WMST,NaN,BCOL,NaN,001,766,Manijeh Moradian,14.0,14.0,F,R 10:10AM-12:00PM,10:10,12:00
6963,WMSTW4210,BLACK GEOGRAPHIES,WMST,NaN,BCOL,NaN,001,764,Marisa Solomon,16.0,15.0,F,R 2:10PM-4:00PM,14:10,16:00

In [372]:
time_counts = df_filtered['start_time'].value_counts().reset_index()
percentages = df_filtered['start_time'].value_counts(normalize=True) * 100
time_counts.columns = ['StartTime', 'Frequency']
percentages.columns = ['StartTime', 'Percentage']
print(time_counts)
print(percentages)

print(df_filtered['contains'].count())

   StartTime  Frequency
0      16:10        330
1      10:10        306
2      13:10        174
3      14:10        160
4      14:40        155
5      11:40        123
6      12:10        102
7      18:10         90
8      08:40         69
9      17:40         33
10     19:00         29
11     08:10         22
12     09:00         13
13     19:10         10
14     08:50          9
15     19:40          8
16     13:00          6
17     09:10          6
18     10:00          5
19     11:00          4
20     15:00          4
21     12:05          3
22     11:10          3
23     14:00          3
24     12:00          3
25     20:10          3
26     18:00          3
27     16:00          3
28     09:05          2
29     18:30          2
30     17:10          2
31     13:30          2
32     12:30          2
33     11:30          2
34     09:30          2
35     15:10          2
36     14:30          1
37     15:30          1
38     04:10          1
39     15:05          1
40     17:30          1
41     10:30          1
start_time
16:10    19.400353
10:10    17.989418
13:10    10.229277
14:10     9.406232
14:40     9.112287
11:40     7.231041
12:10     5.996473
18:10     5.291005
08:40     4.056437
17:40     1.940035
19:00     1.704879
08:10     1.293357
09:00     0.764256
19:10     0.587889
08:50     0.529101
19:40     0.470312
13:00     0.352734
09:10     0.352734
10:00     0.293945
11:00     0.235156
15:00     0.235156
12:05     0.176367
11:10     0.176367
14:00     0.176367
12:00     0.176367
20:10     0.176367
18:00     0.176367
16:00     0.176367
09:05     0.117578
18:30     0.117578
17:10     0.117578
13:30     0.117578
12:30     0.117578
11:30     0.117578
09:30     0.117578
15:10     0.117578
14:30     0.058789
15:30     0.058789
04:10     0.058789
15:05     0.058789
17:30     0.058789
10:30     0.058789
Name: proportion, dtype: float64
1701

In [285]:
import datetime as dt

# Step 1: Parse and extract hour
df_filtered['start_time'] = pd.to_datetime(
    df_filtered['start_time'], format='%H:%M', errors='coerce'
)
df_filtered['start_time_hr'] = df_filtered['start_time'].dt.hour

# Step 3: Bin into time buckets
hour_bins = [8, 10, 12, 14, 16, 18, 20, 22]
hour_labels = ['8 am', '10 am', '12 pm', '2 pm','4 pm', '6 pm','8 pm']
df_filtered['time_bucket'] = pd.cut(
    df_filtered['start_time_hr'], bins=hour_bins, labels=hour_labels, right=False
)
percentages = df_filtered['time_bucket'].value_counts(normalize=True) * 100
print(percentages)

print(df_filtered['start_time_hr'].value_counts().sort_index())

df_filtered['start_time_hr'].shape[0]

df_filtered['start_time_hr'] = df_filtered['start_time'].str.split(':').str[0].astype(int)

# Should now match your raw string prefix counts exactly
print(df_filtered['start_time_hr'].value_counts().sort_index())

print(df_filtered.shape[0])

time_bucket
10 am    23.598820
4 pm     23.058014
2 pm     18.829892
12 pm    17.846608
6 pm      9.636185
8 am      6.637168
8 pm      0.393314
Name: proportion, dtype: float64
start_time_hr
4       1
8     104
9      31
10    337
11    143
12    128
13    235
14    352
15     31
16    400
17     69
18    134
19     62
20      8
Name: count, dtype: int64

AttributeError: Can only use .str accessor with string values!

In [283]:
df_filtered = df_filtered.dropna(subset=['start_time'])
df_filtered['start_time_hr'] = df_filtered['start_time'].str.split(':').str[0].astype(int)

# Should now match your raw string prefix counts exactly
print(df_filtered['start_time_hr'].value_counts().sort_index())
print(df_filtered.shape[0])


df_filtered.to_csv('df_no_start.csv')

start_time_hr
4       1
8     104
9      31
10    337
11    143
12    128
13    235
14    352
15     31
16    400
17     69
18    134
19     62
20      8
Name: count, dtype: int64
2035

# print(df['mil_time_from_hr'].unique())
print(df['mil_time_from_hr'].value_counts())
print(df['mil_time_from'].unique())

print(df.columns.tolist())
print(df.head())

In [117]:
# filtering by fall
filtered_df_fullfall26 = filtered_df_fall[filtered_df_fall.enrollment_status.str.startswith(tuple('F'))]
filtered_df_fullfall26

AttributeError: 'DataFrame' object has no attribute 'enrollment_status'

In [145]:
time_counts = filtered_df_fall['start_time'].value_counts().reset_index()
percentages = filtered_df_fall['start_time'].value_counts(normalize=True) * 100
time_counts.columns = ['StartTime', 'Frequency']
percentages.columns = ['StartTime', 'Percentage']
print(time_counts)

             StartTime  Frequency
0  1900-01-01 10:10:00         87
1  1900-01-01 16:10:00         84
2  1900-01-01 14:10:00         63
3  1900-01-01 14:40:00         36
4  1900-01-01 11:40:00         34
5  1900-01-01 13:10:00         32
6  1900-01-01 12:10:00         29
7  1900-01-01 08:40:00         19
8  1900-01-01 18:10:00         14
9  1900-01-01 17:40:00         12
10 1900-01-01 11:00:00         10
11 1900-01-01 09:10:00          7
12 1900-01-01 09:00:00          6
13 1900-01-01 12:00:00          4
14 1900-01-01 13:00:00          3
15 1900-01-01 11:10:00          1
16 1900-01-01 08:10:00          1
17 1900-01-01 18:30:00          1
18 1900-01-01 13:30:00          1
19 1900-01-01 11:30:00          1
20 1900-01-01 12:30:00          1
21 1900-01-01 20:10:00          1

In [105]:
import datetime as dt

# Step 1: Parse directly and extract hour - don't convert to .dt.time first
df_fall['start_time'] = pd.to_datetime(
    df_fall['start_time'], format='%H:%M', errors='coerce'
)
df_fall['start_hour'] = df_fall['start_time'].dt.hour

# Step 2: Drop rows where parsing failed
df_fall = df_fall.dropna(subset=['start_hour'])
df_fall['start_hour'] = df_fall['start_hour'].astype(int)

# Step 3: Bin into time buckets
hour_bins = [8, 10, 12, 14, 16, 18, 20, 22]
hour_labels = ['8 am - 10 am', '10 am - 12 pm', '12 pm - 2 pm', '2 pm - 4 pm', '4 pm - 6 pm', '6 pm - 8 pm', '8 pm - 10 pm']

df_fall['time_bucket'] = pd.cut(
    df_fall['start_hour'], bins=hour_bins, labels=hour_labels, right=False
)

percentages = df_fall['time_bucket'].value_counts(normalize=True) * 100
print(percentages)

time_bucket
10 am - 12 pm    23.287671
4 pm - 6 pm      19.592227
2 pm - 4 pm      17.521504
12 pm - 2 pm     16.629500
6 pm - 8 pm      12.392482
8 am - 10 am      7.677604
8 pm - 10 pm      2.899012
Name: proportion, dtype: float64

C:\Users\emiik\AppData\Local\Temp\ipykernel_29876\800618368.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fall['start_hour'] = df_fall['start_hour'].astype(int)
C:\Users\emiik\AppData\Local\Temp\ipykernel_29876\800618368.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fall['time_bucket'] = pd.cut(

In [57]:
filtered_df_fall

,course_identifier,dept_code,school_code,course_name,term,section,call_number,instructor,start_time,end_time,days
121,ENGLZ0850,AMLP,SPEC,INTL TEACHING FELLOWS TRAINING,20263,001,11025,Lydia Fass,18:10,20:00,MW 6:10PM-8:00PM
122,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,001,11021,NaN,NaN,NaN,NaN
123,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,002,11022,NaN,NaN,NaN,NaN
124,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,003,11023,NaN,NaN,NaN,NaN
125,ENGLZ0012,AMLP,SPEC,AMER 12 PT PROG INTENSIVE,20263,004,11024,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3864,PSYCW1980,PSYC,SAS,Zuckerman Institute Neuroscience and Cognitive...,20263,001,14277,Sarah Demoya,16:10,17:25,W 4:10PM-5:25PM
3865,PSYCW1951,PSYC,SAS,Cells and Circuits Lab,20263,001,10646,Sarah Demoya,10:10,12:00,F 10:10AM-12:00PM
3866,PSYCW1950,PSYC,SAS,Neuroscience Methods: Cells and Circuits,20263,001,10645,Sarah Demoya,10:10,12:00,R 10:10AM-12:00PM
3867,PSYCW1001,PSYC,SAS,THE SCIENCE OF PSYCHOLOGY,20263,001,10631,Patricia G Lindemann,13:10,14:25,TR 1:10PM-2:25PM
3868,PSYCW1001,PSYC,SAS,THE SCIENCE OF PSYCHOLOGY,20263,002,10633,Natalie Brito,10:10,11:25,TR 10:10AM-11:25AM